### PR TITLE
Master

### PR DESCRIPTION
**Pull request by AndresPozo**
MosaicPlanner v1

### CODE REVIEW

**Comment by jconejero** [comment]
Thank you Andrés. I'll include MosaicPlanner in the incoming 1.8.4.1194 version of PixInsight.

Congratulations on a very nice and useful script!

**Comment by jconejero** [comment]
Hi Andrés,

I see that you have included two images (rotateCCW.png and rotateCW.png) with your MosaicPlanner script. The platform already has two standard icons for these tasks, namely:

:/icons/picture-rotate-left.png
:/icons/picture-rotate-right.png

which should be used instead. They are of course available in scaled versions for multiple resolutions. I can make the changes for you in MosaicPlanner.js and commit the modified version here. Do you agree?

**Comment by AndresPozo** [comment]
I agree.
I use the script core-icons-1.8.js for choosing the icons in my scripts. The icons that you suggest are not in the list. It would be very helpful if you would update the script with the available icons of the latest version.

**Comment by jconejero** [comment]
Hi Andrés,

I have just commited a new CoreIconsBrowser script. It belongs to the official distribution from now on. I'll update the version in PI forum too. Thanks for pointing this out.

**Pull request merged**
