### PR TITLE
Add minimum/maximum properties for SNRWeight, Eccentricity, FWHM to SubframeSelector

### PR DESCRIPTION
**Pull request by dvonhand**
I'm not sure what the proper procedure is, but I added a little bit of functionality to the SubframeSelector script to recognize new keywords.  I got tired of sorting images and editing the selection/approval formulas for each batch of images, so I introduced six new keywords to make my formulas essentially constant.

Let me know if patches like this are welcome and I will send them along as I make them.  If not, no hard feelings...

### CODE REVIEW

**Comment by jrussek** [comment]
:+1: 
yes please! Why is this not merged? I do not understand.. it is so tedious without it.
I basically patched the same functionality in (just calculating a factor between min/max to each subframe, but to achieve the same end..)

**Comment by jconejero** [comment]
I am sorry for the delay in merging this pull request. I was waiting for the author to review the changes, but time passed and I forgot it. Now I have taken a look and there is no reason for not including this functionality IMO. Thank you Johannes for the heads up, and of course thanks to dvonhand for this contribution.

By the way, we are now working on the [SubframeSelector tool](https://github.com/PixInsight/PCL/tree/master/src/modules/processes/contrib/cleger/SubframeSelector), written by Cameron Leger based on this original script by Mike Schuster. The SubframeSelector tool will be included in the incoming version 1.8.6 of PixInsight, and I think we should have these predefined keywords also available on it.

**Comment by jrussek** [comment]
thanks @jconejero! Glad my poke was a great success :)
May I suggest to add other aggregates besides min/max as well?

**Comment by jconejero** [comment]
Yes, of course!

So far the SubframeSelector module has the following predefined variables:

Index, Weight, FWHM, Eccentricity, SNRWeight, Median, MedianMeanDev, Noise, Stars, StarResidual, NoiseRatio, FWHMMeanDev, EccentricityMeanDev, StarResidualMeanDev

Each property (excluding Index) also has a Median, Min, and Max version, e.g. FWHMMin, which are computed across all subframes.

Each property (excluding Index) also has a Sigma version, e.g. SNRWeightSigma, where the value is represented in sigma units of the Mean Absolute Deviation from the Median.

Please let us know if you have more properties besides these, or anything else you'd like to have included.

**Comment by jrussek** [comment]
Those look great, thanks @jconejero.

**Comment by jrussek** [comment]
Oh, the only other issue I've had with the script is the lack of being able to run more than one process at once and make use of multiple cores :)

**Comment by jconejero** [comment]
The SubframeSelector tool is fully multithreaded; you're gonna love it! ;)

**Comment by dvonhand** [comment]
Thanks for reaching out!  I found all these in my spam folder.  I appreciate it.  I look forward to taking advantage of the additional properties in the next release cycle.

Dusty

**Comment by jrussek** [comment]
I gave it a try already (I think, found it in a mailing thread and downloaded a release from a fork from PCL). @jconejero where would you like us to add feature requests for that module?
I already found a problem when star registration fails during measurement and I had no option to select what to do on error, nor did the error message tell me which frame caused the issue :)

**Pull request merged**
