### PR TITLE
Support for high DPI (scaled) displays

### PR DESCRIPTION
**Pull request by AndresPozo**
The scripts have been tested and fixed in PI 1.8.4 with UI scales of
1.0, 1.3 and 2.0, in Windows 7 and Ubuntu 14.04.

### CODE REVIEW

**Comment by jconejero** [comment]
Hi Andrés, thank you for this update. I'm going to merge it now, and will include these versions in the new 1.8.4.1185 release of PixInsight.

Just a few notes about the changes you've made. The following properties:

Sizer.margin
Sizer.scaledMargin

are equivalent (synonyms). Similarly,

Sizer.spacing
Sizer.scaledSpacing

are also equivalent. That is, for the Sizer object, automatic scaling of spacings and margins is enabled by default. This is by design to facilitate the automatic conversion of existing source code to the new scaled UI (feasible in this case because sizer spacings and margins are in a 99.99% of the cases specified as literal scalable pixel values in existing PJSR and PCL code).

That said, using the scalingXXX properties improves readability of source code, so these changes are welcome.

Also note that the Sizer.addSpacing() method has changed in version 1.8.4:

void Sizer.addSpacing( int size[, Boolean autoScaling=true] )

As you see, this method has now a second parameter to control whether the size value in pixels must be scaled automatically (because it is specified in logical pixels) or taken literally (physical pixels). This also facilitates automatic code adaptation because autoScaling is true by default. As happens with spacing/scaledSpacing, there are new Sizer.addScaledSpacing() and Sizer.insertScaledSpacing() methods for improved readability of newly produced code.

**Comment by jconejero** [comment]
I've detected a small bug: When the ImageSolver script is launched for an image that has no WCS solution, if you click the Reset button the following happens:

ImageSolver.js, line 505: Error: Point.Point(): invalid argument type: numeric value expected.

Line 505 is:

this.coords_Editor = new CoordinatesEditor(this, new Point(metadata.ra, metadata.dec), labelWidth1, spinBoxWidth, coordinatesTooltip);

The error happens because the metadata.ra and metadata.dec properties have been initialized to null.

The importance of this issue is small in practice IMO (it gets fixed by just launching the script on a solved image). I think we can release this version with build 1185 despite this bug; let me know (quickly, please!) if you prefer to revert your scripts to the previous version instead, or if you can fix this problem easily (I think so), please release a pull request.

**Comment by AndresPozo** [comment]
I can fix it today but not before 10:00 (UTC+2)

**Comment by jconejero** [comment]
Hi Andrés,

No need to hurry up so much! if you can fix it tomorrow, that would be 
perfectly fine.

Unfortunately, I have just discovered a small bug in the core 
application a while ago, and I want to fix it before the release, so 
there is probably even more time...

Thank you so much for your great work!

**Pull request merged**
