### PR TITLE
Create LocalFuzzyHistogramHyperbolizaion.js

### PR DESCRIPTION
**Pull request by fweidenbusch**
Hi Juan,

here is the pull request for the LFHH script. To be honest, I still have some problems with GutHub. I hope everything is ok.

Cheers,
Frank

### CODE REVIEW

**Comment by jconejero** [comment]
Hi Frank,

Welcome to our open-source GitHub repositories, and thank you so much for this commit. I'll take a look at your code and will prepare the release of this script as an official update.

**Comment by fweidenbusch** [comment]
Hi Juan,

thank you very much. One question to the documentation. I think I had to submit also all images which are included in the document. How can I do this?

**Comment by jconejero** [comment]
Hi Frank,

Yes, you're right, we need all of the images. Simply create a new pull request with the images on the same folder as the .pidoc file you already have submitted: Reference-Documentation/scripts/LocalFuzzyHistogramHyperbolization/

On your forked repository, copy the images to the corresponding folder under your "patch-1" branch, but make the pull request to the master branch of our Reference-Documentation repository. Let me know if you need more information.

**Comment by fweidenbusch** [comment]
Hi Juan,

I hope I did it right. Please tell me if not.

**Pull request merged**
